vim.lsp.enable("svelte")
vim.lsp.enable("lua_ls")
vim.lsp.enable("nixd")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("cssls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("qmlls")
vim.lsp.enable("clangd")
